import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from '../pages/api/auth/NextAuthProvider';
import { RecoilStateProvider } from "@/pages/api/auth/RecoilStateProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <NextAuthProvider>
            <RecoilStateProvider>
              {children}
            </RecoilStateProvider>
          </NextAuthProvider>
      </body>
    </html>
  );
}
